LABEL_SPOT = 'SPOT'
LABEL_SERVER = 'Server:'
LABEL_VIDEO_PATH = 'Video path:'
LABEL_PROCESS = 'Process'
LABEL_VIDEO_HOT = 'Is this video white hot?'
LABEL_VIDEO_BORDER = 'Are there any numbers or borders in the video?'
LABEL_LOCAL_SERVER = 'Local'
LABEL_REMOTE_SERVER = 'Remote'
LABEL_YES = 'Yes'
LABEL_NO = 'No'
LABEL_TERMINATE = 'Terminate'
LABEL_VIDEO_DETECTION = 'Which video frames do you want to display?'
LABEL_VIDEO_DETECTION = 'Do you want video frames only when detected?'

COLOR_GREEN = 'green'
COLOR_GRAY = 'gray'

DICT_CROP_VIDEOHOT_KEY = 'invert'
DICT_CROP_VIDEOBORDER_KEY = 'crop'
DICT_CROP_CROPTOP_KEY = 'cropTop'
DICT_CROP_CROPLEFT_KEY = 'cropLeft'
DICT_CROP_CROPBOTTOM_KEY = 'cropBottom'
DICT_CROP_CROPRIGHT_KEY = 'cropRight'